"$schema" = "./node_modules/wrangler/config-schema.json"
name = "flat-web"
compatibility_date = "2026-05-17"
main = "./worker/index.ts"

[assets]
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "flat-web"
database_id = "1df6fb45-2f5a-4a9f-8c7d-ce8555659249"
migrations_dir = "migrations"
